const API_PATH = {
  apiUserLogin: "/api/user/login",
  apiAddUser:"/api/user/add",
  apiGetUser: "/api/users/detail/",
  apiEditUser: "/api/users/edit",
  apiChangePassword: "/api/change/password",
  apiForgetPassword:"/api/forgot/password",
  apiCourseList:"/api/course",
  apiCourseDetails:"/api/course/detail",
  apiChapterList:"/api/chapter/list/",
  showPackage:"/api/show_package/",
  apiChapterDetails:"/api/chapter/detail/",
  apiShowClientPackage:"/api/show_client_package/",
  apiShowAllotPackage:"/api/show_allotpackage/",
  apiChangeChapterStatus:"/api/change_chapter_status/",
  apiGetChapterStatus:"/api/get_chapter_status/",
  apiQuizList:"/api/quiz/list/",
  apiAnswerCheck:"/api/answer_check/",
};
export default API_PATH;
