const API_PATH = {
  apiUserLogin: "/api/user/login",
  apiAddUser: "/api/singup/",
  apiGetUser: "/api/users/detail/",
  apiEditUser: "/api/users/edit",
  apiChangePassword: "/api/change/password",
  apiForgetPassword: "/api/forgot/password",
  apiCourseList: "/api/course",
  apiCourseDetails: "/api/course/detail",
  apiChapterList: "/api/chapter/list/",
  showPackage: "/api/show_package/",
  apiChapterDetails: "/api/chapter/detail",
  apiShowClientPackage: "/api/show_client_package/",
  apiShowAllotPackage: "/api/show_allotpackage/",
  apiChangeChapterStatus: "/api/change_chapter_status/",
  apiGetChapterStatus: "/api/get_chapter_status/",
  apiQuizList: "/api/quiz/list/",
  apiAnswerCheck: "/api/answer_check/",
  apiCategoryList: "/api/category/list",
  apiServiceList: "/api/service_list_client/",
  apiEventList: "/api/event_list_client/",
  apiBannerList: "/api/banner_list_client/",
  apiChapterClientList: "/api/chapter_client_list/",
  apiAddCertificate:"api/add_certificate/",
  apiAddQuery:"api/query_form/",
};
export default API_PATH;
