const API_PATH = {
  apiUserLogin: "/api/user/login",
  apiAddUser: "/api/singup/",
  apiChangePassword: "/api/change/password",
  apiForgetPassword: "/api/forgot/password",
  apiEditUser: "/api/users/edit",
  apiGetUser: "/api/users/detail/",
  showPackage: "/api/show_package/",
  apiShowClientPackage: "/api/show_client_package/",
  apiShowPackageCourse: "/api/show_package_course/",
  apiAllotPackage: "/api/allot_package/",
  apiBuyPackage: "/api/buy_package/",
  apiAllotCourse: "/api/allot/course",
  apiCourseList: "/api/course",
  apiCourseDetails: "/api/course/detail",
  apiChapterClientList: "/api/chapter_client_list/",
  apiQuizList: "/api/quiz/list/",
  apiAnswerCheck: "/api/answer_check/",
  apiChapterList: "/api/chapter/list/",
  apiChapterDetails: "/api/chapter/detail",
  apiGetChapterStatus: "/api/get_chapter_status/",
  apiChangeChapterStatus: "/api/change_chapter_status/",
  apiEventList: "/api/event_list_client/",
  apiBannerList: "/api/banner_list_client/",
  apiAddQuery: "api/query_form/",
  apiAddCertificate: "api/add_certificate/",
  apiServiceList: "/api/service_list_client/",
  apiCategoryList: "/api/category/list",
};
export default API_PATH;
